apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threescale-prod
spec:
  destination:
    namespace: threescale-production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 3scale/
    repoURL: https://github.com/rpscodes/3scale-gitops.git
    targetRevision: prod
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true